Bugfix for TypeError, comparison needed to be bytes instead of str.
  File "/home/ppx/evernote-publisher/lib/generator.py", line 187, in contentWithTranslatedAssets
    elif filenameLower.endswith('.octet-stream') and resource.data.body[0:3].lower().startswith('<svg'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str